
import { Prompt } from './types';

export const GENRES = ['All', 'Drama', 'Crime', 'Fantasy', 'Horror', 'Historical', 'Romance', 'Sci-Fi', 'Thriller'];

export const PROMPTS: Prompt[] = [
  { line: "When real life is wanting, one must create an illusion.", tags: ["Dreams", "Life"], genre: "Drama" },
  { line: "He had seen the devil on three different occasions.", tags: ["Bible", "Criminal Justice", "Evil", "Politics", "Racism"], genre: "Horror" },
  { line: "At this job, you got to keep your mind busy or else it will wander.", tags: ["Marriage", "Spirituality", "Work"], genre: "Drama" },
  { line: "It's on the tip of my brain.", tags: ["Aging", "Life", "Marriage"], genre: "Drama" },
  { line: "What is a soulmate anyway?", tags: ["Destiny", "Love", "Marriage"], genre: "Romance" },
  { line: "He remembered being impatient to grow up. Now he was ready.", tags: ["Death", "Life"], genre: "Drama" },
  { line: '"True, but wishes granted are often the stuff of nightmares."', tags: ["Dreams", "Family", "Life", "Love", "Marriage", "Politics", "Sex", "Travel", "Work"], genre: "Fantasy" },
  { line: '"Why is it you can\'t forget what you really want to forget?" (Ozick)', tags: ["Criminal Justice", "Family", "Life", "Love", "Marriage", "Racism", "Sex"], genre: "Drama" },
  { line: "Why did Uncle Mark have such a hard time staying out of prison?", tags: ["Criminal Justice", "Family", "Prison"], genre: "Crime" },
  { line: "So the matter has remained. A book has appeared under my name.", tags: ["Bible", "Conspiracy Theory", "Hustle", "Magic", "Marriage", "Prison", "Racism", "Sex", "Strange Stuff"], genre: "Thriller" },
  { line: '"Believe me, everything looks like a noose if you stare at it long enough."', tags: ["Criminal Justice", "Love", "Marriage", "Politics", "Prison", "Racism", "Work"], genre: "Thriller" },
  { line: '""You have your machine to beat and I have mine."" (Colson Whitehead)', tags: ["Criminal Justice", "Destiny", "Hustle", "Life", "Politics", "Racism", "Work"], genre: "Sci-Fi" },
  { line: '"The end was in the beginning." (Ralph Ellison, Invisible Man)', tags: ["Destiny", "History", "Life", "Love", "Marriage", "Politics"], genre: "Sci-Fi" },
  { line: "Living like angels can be just as destructive as living like animals.", tags: ["Bible", "Dreams", "Evil", "Life", "Marriage", "Sex"], genre: "Drama" },
  { line: "But perhaps the universe is suspended on the tooth of some monster.", tags: ["Bible", "Life", "Magic", "Mythology", "Spirituality"], genre: "Fantasy" },
  { line: '"How will I feel about my decision in 10 months?" (Elle Kaplan)', tags: ["Life", "Love", "Marriage", "Travel", "Work"], genre: "Drama" },
  { line: "The powerful are not as powerful as they seem—nor the weak as weak.", tags: ["Bible", "Criminal Justice", "Politics", "Prison", "Racism"], genre: "Drama" },
  { line: "This happened or maybe it did not. The time is long past and memories are blurred.", tags: ["Conspiracy Theory", "History", "Mythology", "Strange Stuff"], genre: "Thriller" },
  { line: "Have you ever witnessed the transformation of human beings into monsters?", tags: ["Criminal Justice", "Politics", "Poverty", "Racism"], genre: "Horror" },
  { line: "Like all of the best conspiracy theories, this one begins with a grain of truth.", tags: ["Conspiracy Theory", "History", "Mythology", "Politics"], genre: "Thriller" },
  { line: '"The ordinary can be like medicine." (Sherman Alexie, The Lone Ranger and Tonto Fistfight in Heaven)', tags: ["Family", "Life", "Love", "Marriage"], genre: "Drama" },
  { line: '""Don\'t set sail using someone else\'s star."" (Allahya Kwada)', tags: ["Life", "Luck", "Travel", "Work"], genre: "Drama" },
  { line: '"How can we expect a cultured man not to commit a murder, when he is surrounded by injustice?"', tags: ["Criminal Justice", "Hustle", "Life", "Work"], genre: "Crime" },
  { line: "You had just as well try to bail the Atlantic by pouring the water out with a teacup.", tags: ["Aging", "Life", "Marriage", "Politics"], genre: "Drama" },
  { line: '"History makes harsh demands of us all." (Ralph Ellison, Invisible Man)', tags: ["Destiny", "History", "Life", "Politics"], genre: "Historical" },
  { line: '"How long does it take to forget a hole in your self." (Colson Whitehead)', tags: ["Hustle", "Life", "Love", "Work"], genre: "Drama" },
  { line: "Lies My Wife Told Me", tags: ["Family", "Love", "Marriage", "Sex"], genre: "Romance" },
  { line: '"Why do poets think They can change the world? The only life they can influence is their own."', tags: ["Destiny", "Life", "Love", "Writing"], genre: "Drama" },
  { line: "Manna was a test", tags: ["Bible", "Destiny", "Marriage", "Spirituality"], genre: "Fantasy" },
  { line: "There is a story, for instance, that has very much the ring of truth.", tags: ["History", "Magic", "Mythology"], genre: "Historical" },
  { line: "This happened or maybe it did not.", tags: ["Conspiracy Theory", "History", "Magic"], genre: "Thriller" },
  { line: '"That\'s another story I would like to hear." (Allahya Kwada, African Love Stories)', tags: ["History", "Magic", "Mythology"], genre: "Fantasy" },
  { line: "No one in my family, not one of my friends or classmates, received any sort of sex education.", tags: ["Dreams", "Life", "Strange Stuff"], genre: "Drama" },
  { line: "In another time, in other, less civilized places, desperate men did desperate things.", tags: ["History", "Life", "Love"], genre: "Historical" },
  { line: '"Why is it you can\'t forget what you really want to forget?" (Cynthia Ozick)', tags: ["Family", "Life", "Love"], genre: "Romance" },
  { line: "I miss wet dreams.", tags: ["Aging", "Marriage", "Sex"], genre: "Drama" },
  { line: "Picking a fight.", tags: ["Aging", "Life", "Strange Stuff"], genre: "Drama" },
  { line: "There was a time when I lived off six dollars a day.", tags: ["Hustle", "Life", "Poverty"], genre: "Drama" },
  { line: "The madman is not the man who has lost his reason. The madman is the man who has lost everything except his reason.", tags: ["Life", "Spirituality"], genre: "Thriller" },
  { line: '"You don\'t grasp the beauty of the destruction of words." (George Orwell, 1984)', tags: ["Death", "Strange Stuff"], genre: "Sci-Fi" },
  { line: "IF LOVE DOESN'T PREVAIL, WHO WANTS TO LIVE IN THIS WORLD?", tags: ["Love", "Marriage"], genre: "Romance" },
  { line: '"The older I get, the more this magic madness seems to fall upon me."', tags: ["Life", "Magic"], genre: "Fantasy" },
  { line: "And thank God for it, I want nothing; God give everyone such a life.", tags: ["Love", "Spirituality"], genre: "Drama" },
  { line: "He didn't realize she was the weak eyed sister until he met her.", tags: ["Bible", "Love"], genre: "Romance" },
  { line: "There was something about him that liked to pick fights.", tags: ["Love", "Racism"], genre: "Drama" },
  { line: "He liked making love to her the most because that was when she was most vulnerable.", tags: ["Marriage", "Sex"], genre: "Romance" },
  { line: "It was described as a radical act.", tags: ["Strange Stuff"], genre: "Drama" },
  { line: "A child bride was sold on Facebook.", tags: ["Life"], genre: "Crime" },
  { line: "Be not afraid of going too slowly. Be afraid of standing still - Jamaican Proverb", tags: ["Life"], genre: "Drama" },
  { line: "Life can only be understood backwards; but it must be lived forwards.", tags: ["Love"], genre: "Drama" },
  { line: "Everything went head over heels to the devil.", tags: ["Life"], genre: "Horror" },
  { line: "Today he had a thought about good vibes and it scared him.", tags: ["Marriage"], genre: "Drama" },
  { line: "I just want to laugh out loud like we used to.", tags: ["Luck"], genre: "Drama" },
  { line: "She was born in the year of the snake, and believed her parents had sold her soul.", tags: ["Love"], genre: "Fantasy" },
  { line: "It's only love that gets you through.", tags: ["Destiny"], genre: "Romance" },
  { line: "At times, I feel that I am futility fighting a battle against my own mind.", tags: ["Politics"], genre: "Drama" },
  { line: "After so many lies, nobody believes anybody anymore.", tags: ["Life"], genre: "Thriller" }
];